### ISSUE TITLE
Using with require.js and ROSlib.js results in error

### ISSUE THREAD

**Issue by Pro** [asyncly/EventEmitter2#100]
When using require.js and https://github.com/RobotWebTools/roslibjs I get the error
"EventEmitter2" not defined.

See this fiddle:
http://jsfiddle.net/mKyEA/1/

and the discussion on StackOverflow:
http://stackoverflow.com/questions/19362966/require-js-shim-configuration-for-eventemitter2

**Comment by RangerMauve** [comment]
Seems to have been closed already
