### ISSUE TITLE
Error event listener not capturing thrown event

### ISSUE THREAD

**Issue by jeffwhelpley** [asyncly/EventEmitter2#117]
My expectation is that if an error is thrown within an event listener, the error event would be emitted. It doesn't seem like the lib works that way now, but would it be possible to add that?

```javascript
ee.on('error', function (err) {
    console.log(err);
});

ee.on('some.other.event', function () {
    throw Error('blah');
});

ee.emit('some.other.event');
```

Without this, the error would bubble up to the process/domain unhandled error, which I would like to avoid. If you agree this should be a feature and give me some direction I don't mind doing a PR.

**Comment by cxreg** [comment]
This is what node's domains (and whatever eventually replaces it) is for.  This would provide a confusing and inconsistent experience as synchronous errors would emit 'error' and async ones would not.

**Comment by RangerMauve** [comment]
Adding a try catch around everything might be a bit much. Not sure if it'd be worth it, or even really expected considering it's different from the regular EventEmitter behavior.
