### ISSUE TITLE
Cause effect behavior to EventEmitter2

### ISSUE THREAD

**Issue by geophoenix** [asyncly/EventEmitter2#119]
Hello, i want to ask how to achieve this `Cause=>Effect` behavior using EventEmitter2?

To be a little more accurate take a look at this repository 

https://github.com/olado/causeeffect

it is possible to do, something like `object.on(['effect:1','effect:2','effect:3'],'effect:ok');` which pretty much say that the object will trigger/emit `effect:ok` only when `effect:1`,`effect:2`,`effect:3` are all emitted to it.

**Comment by RangerMauve** [comment]
I think this might be outside of the scope of the library. You may want to wrap over it to achieve the functionality you want. Maybe by tracking which events have been emitted in the past using `onAny`?
