### ISSUE TITLE
Inconsistent module export

### ISSUE THREAD

**Issue by matthewwithanm** [asyncly/EventEmitter2#121]
When used as an AMD module, EventEmitter2 exports the EventEmitter constructor. In other words, you would use it like this (with CommonJS wrapping style):

```javascript
define(function (require) {
    var EE = require('EventEmitter2');
});
```

However, when using CommonJS modules, the object is just added to `exports`, so it's used like this:

```javascript
var EE = require('EventEmitter2').EventEmitter2;
```

It seems to me that these should be consistent. (This came up in the [webpack Gitter room][1] because it led to some confusion.) I'm not sure how best to resolve the inconsistency, but if you wanted to address it without breaking backwards compatibility, you could always export the constructor function but add an "EventEmitter2" reference that points back to itself. In other words:

```javascript
  EventEmitter.EventEmitter2 = EventEmitter;

  if (typeof define === 'function' && define.amd) {
     // AMD. Register as an anonymous module.
    define(function() {
      return EventEmitter;
    });
  } else if (typeof exports === 'object') {
    // CommonJS
    module.exports = EventEmitter;
  }
  else {
    // Browser global.
    window.EventEmitter2 = EventEmitter;
  }
```

This way, it could be used either way `require('eventemitter2')` or `require('eventemitter2').EventEmitter2` with either module system, preserving backwards compatibility.

[1]: https://gitter.im/webpack/webpack

**Comment by RangerMauve** [comment]
#156
