### ISSUE TITLE
Event listeners not added when delimiter at the start

### ISSUE THREAD

**Issue by RangerMauve** [asyncly/EventEmitter2#128]
I noticed that adding the delimiter as the first character in the event name meant that the listener is never added to the listener tree.

Example: 

``` javascript
var events = new EventEmitter2({delimiter:"/"});
var log = console.log.bind(console);

events.on("/foo/bar",log);
events.emit("/foo/bar","Doesn't get logged");
```

**Comment by ash-developer** [comment]
does't work for { wildcard: true }

`var EventEmitter2 = require('eventemitter2');
var events = new EventEmitter2({
    wildcard: true,
    delimiter: "/"
});

var log = console.log.bind(console);

events.on("/foo/bar", log);
events.emit("/foo/bar", "Doesn't get logged");`

**Comment by lelandmiller** [comment]
I just tried running with the snippet from @ash-developer in node on eventemitter2@2.2.1 and it seemed to work, unless I missed something. I have been working with a similar setup where the delimiter is the first character frequently with no issues on this version. Has this issue been fixed?

**Comment by RangerMauve** [comment]
@lelandmiller  If it's working for you with the latest release, then it's probably fine. What delimiter are you using for the wildcards?

**Comment by RangerMauve** [comment]
Sorry, missed part of the message. If you're saying it works, then I'll close this issue until somebody else reports that it's a problem.
