### ISSUE TITLE
Wildcards Not working at All

### ISSUE THREAD

**Issue by willglaub** [asyncly/EventEmitter2#130]
Working from a direct git-clone of this repo, or from the npm retrieved version, the wild-card feature does not work, either with the examples from the readme.md, or from examples I contrive.  The only way to get the wildcard event listener to be called, is by firing an event with the wildcard actually in the event string.  Firing 'foo.bar' for example, does not work, for a wild-carded foo namespace.  It is as if the asterisk is just being literally matched.  See screenshot from REPL attached, where I tried a variety of things, with no success on wildcards.  Is this something I'm doing wrong, or an actual issue that has emerged with recent changes?
![repl_screenshot](https://cloud.githubusercontent.com/assets/2789851/4244499/79513770-3a22-11e4-80bc-309e201db3c6.png)

**Comment by fresheneesz** [comment]
So wildcards aren't enabled by default?

**Comment by fresheneesz** [comment]
Confirmed, wildcards aren't enabled by default. The documentation isn't very clear on this, and I opened an issue for that. But this should be closed
