### ISSUE TITLE
removeAllListeners based on listener instead of event

### ISSUE THREAD

**Issue by zumoshi** [asyncly/EventEmitter2#133]
hi,
given the same function is responsible for multiple events , i would like to have a function to remove all listeners (for any event) that points to that function.

    var f = function (arg){
        //do sth based on this.event
    }
    server.on('foo.*',f);
    server.on('bar.*',f);
    server.on('message',f);
    //...
    server.removeAllListeners(f);
    //now f should not have any listeners anymore

we can check for typeof parameter to removeAllListeners and change its behavior if it is a function while keeping it compatible if parameter is a string.

**Comment by RangerMauve** [comment]
This seems like a pretty unique use case and is very different from the regular EventEmitter API. I'd rather not overload removeAllListeners. If there's a bunch of people wanting this feature then maybe it'd be more appealing. Else, it might make sense to just have a utility that does this.
