### ISSUE TITLE
Unknown global: COUNTER_NET_SERVER_CONNECTION when tests are run in node

### ISSUE THREAD

**Issue by fresheneesz** [asyncly/EventEmitter2#140]
When the tests are run via `npm test` in node v0.10.29, i get the following output at the end:

```
OK: 203 assertions (53ms)
Unknown global: COUNTER_NET_SERVER_CONNECTION

assert.js:92
  throw new assert.AssertionError({
        ^
AssertionError: Unknown global founded
    at process.exports.httpTest (D:\billysFile\code\javascript\nodejs\modules\EventEmitter2\test\common.js:118:14)
    at process.emit (events.js:117:20)
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

Is there a reason you're explicitly testing for globals? Since these aren't really fully in your control, I'd suggest not running this test.

**Comment by fresheneesz** [comment]
As a matter of fact, when I comment out the failling assertion, I get these additional console logs indicating other global variables that aren't in your list:

```
Unknown global: COUNTER_NET_SERVER_CONNECTION
Unknown global: COUNTER_NET_SERVER_CONNECTION_CLOSE
Unknown global: COUNTER_HTTP_SERVER_REQUEST
Unknown global: COUNTER_HTTP_SERVER_RESPONSE
Unknown global: COUNTER_HTTP_CLIENT_REQUEST
Unknown global: COUNTER_HTTP_CLIENT_RESPONSE
```

**Comment by RangerMauve** [comment]
Any idea where this might be coming from? I'm currently investigating this.

**Comment by RangerMauve** [comment]
Seems to be part of a bunch of globals defined [here](https://github.com/nodejs/node-convergence-archive/blob/master/src/node_counters.cc). Looking into having the tests account for them.
