### ISSUE TITLE
Suggestion: ifon/ifoff methods

### ISSUE THREAD

**Issue by fresheneesz** [asyncly/EventEmitter2#142]
I'm building a system that relies heavily on events, and especially emitting events that begin their life as dom events. I don't want every single object i write to bind dom events, because I fear the performance gods. So what I'd like to do is bind events only on the condition that someone up the line has bound an event that requires knowing when a particular dom event has happened. Therefore, I've determined I want something like the following interface:

```javascript
// should be triggered when the first listener for the 'click' event is added
// (regardless of whether its done through on, onAny, once, or many)
emitter.ifon('click', function() {
   domNode.addEventListener('click', someCallback)
})
// should be triggered when the last listener for the 'click' event is removed
// (regardless of whether this is done through off, offAny, or as a result of 'once' or 'many' calls being fulfilled
emitter.ifoff('click', function(callback) {
   domNode.removeEventListener('click', someCallback)
})
```

I'm also wondering what your opinion is about the performance related to event emit chains. Without this kind of feature, the system I'm building would essentially attach a listener to every single dom object on the page. I'm assuming that would be no good.

**Comment by fresheneesz** [comment]
I just realized this could also be used as an alternative to `onAny`, since you could always use `ifon` to register new callbacks as needed.

**Comment by hij1nx** [comment]
Hmm, my immediate reaction is `-1` on this idea because it makes the API surface area larger, it's also a pretty unique use case. If `onAny` could be used as an alternative to your proposal, are there any new/discrete benefits that this offers?

**Comment by fresheneesz** [comment]
I actually said `ifon` could be used as an alternative to `onAny` - not the other way around. The benefit is that you can know when an event is needed and when its not. `onAny` doesn't do that for you. If `ifon` could be called without an event so that its called for any event, then it could be used as an alternative to `onAny` cause you could do something like:

```javascript
emitter.ifon(function(event, callback) {
   emitter.on(event, function() {
      // do whatever you'd do in onAny
   })
})
```

**Comment by fresheneesz** [comment]
Deleted the comment i just wrote (like 30 minutes ago) cause I realized i'm wrong. `ifon` can't be used to implement or as an alternative to `onAny`. I think my brain was trying to tell me that it solves the use case *I* had for `onAny`. My use case for using `onAny` is bubbling events from one emitter through another (so that emitter A emits all the events emitter B emits). 

But again, the major things you get with `ifon` is that you can know when someone is listening for an event or not, and that allows you to *not* attach lower level event handlers until they're needed - which could potentially be very beneficial for performance.

**Comment by cxreg** [comment]
Have you looked into using the newListener event for this problem?

**Comment by fresheneesz** [comment]
It might be possible to implement `onAny` using `newListener` and `removeListener`. Problem witih `newListener` is that its emitted before the listener is actually attached. I was pretty unclear what the sequence of events are in that, so I ended up implementing it another way.

**Comment by RangerMauve** [comment]
Gonna close this since the discussion seems to have died. Re-open it if you need any more clarification.
