### ISSUE TITLE
licence request

### ISSUE THREAD

**Issue by soliton4** [asyncly/EventEmitter2#143]
hi,
i used eventemitter2 here:

https://github.com/soliton4/promiseland-webframework/blob/master/frameworkClient/Eventemitter.js

pls tell me if i have to add some additional licencing info or if you want me to mention you in the thank yous

best wishes
sol

**Comment by hij1nx** [comment]
My main concern is for you :) I'm concerned that if you don't use it as a module you will find it quite painful to maintain your library. Any reason *not* to use it as a module?

**Comment by soliton4** [comment]
what do you mean "not using it as a module"?

https://github.com/soliton4/promiseland-webframework/blob/master/frameworkClient/client.pland#L4

**Comment by soliton4** [comment]
ah you mean a github submodule?  
well i dont want to introduce many submodules. making it a slim demo implementation.  
and at this point i do not forsee any further use of it than emiting a connect / disconnect event. which it does quite well.

**Comment by hij1nx** [comment]
lol, not github submodules. I don't know what a .pland file is, or how your project works, but i'm talking about commonJS/ES modules

**Comment by soliton4** [comment]
pland is the extension for my javascript language extension called promiseLand  
http://promise-land.net/  
it includes javascript strict mode so it is not a new language
all promiseland modules have a commonjs and amd compatible module header.
require is a keyword that lets you use your module loader.  

so in short - i am using it as a module ;)

**Comment by hij1nx** [comment]
ok, well sounds great! no worries about the license :)
