### ISSUE TITLE
Always make require('eventemitter2') return the object

### ISSUE THREAD

**Issue by DelvarWorld** [asyncly/EventEmitter2#146]
based on https://github.com/webpack/webpack/issues/829

It does indeed seem like bad practice to make AMD load a module one way and require load it another way. Since `events = require('eventemitter2').EventEmitter2` seems a little redundant, it would be nice if `events = require('eventemitter2')` worked instead

**Comment by mjw56** [comment]
:+1:

**Comment by RangerMauve** [comment]
Pretty sure the reasoning behind his was to make it behave the same as the [events module](https://nodejs.org/api/events.html) in Node

**Comment by ScreenDriver** [comment]
:+1:

**Comment by zack9433** [comment]
:+1:

**Comment by am80l** [comment]
:+1:

**Comment by eu-ge-ne** [comment]
+1

**Comment by kmalakoff** [comment]
When using webpack, it picks up the AMD version: 

```
	  if (true) {
	     // AMD. Register as an anonymous module.
	    !(__WEBPACK_AMD_DEFINE_RESULT__ = function() {
	      return EventEmitter;
	    }.call(exports, __webpack_require__, exports, module), __WEBPACK_AMD_DEFINE_RESULT__ !== undefined && (module.exports = __WEBPACK_AMD_DEFINE_RESULT__));
	  } else if (typeof exports === 'object') {
	    // CommonJS
	    exports.EventEmitter2 = EventEmitter;
	  }
	  else {
	    // Browser global.
	    window.EventEmitter2 = EventEmitter;
	  }
```

Making libraries fail due to an inconsistent API like in measure https://github.com/andrewjstone/measure/issues/1

```
var EventEmitter = require('eventemitter2').EventEmitter2;

// Uncaught TypeError: EventEmitter is not a function
var ee = module.exports = new EventEmitter({
  wildcard: true
});
```

Unless the API has multiple exports, just export the EventEmitter.

```
  if (typeof define === 'function' && define.amd) {
     // AMD. Register as an anonymous module.
    define(function() {
      return EventEmitter;
    });
  } else if (typeof exports === 'object') {
    // CommonJS
    module.exports = EventEmitter;
  }
  else {
    // Browser global.
    window.EventEmitter2 = EventEmitter;
  }
```


To provide backwards compatibility, you can add EventEmitter to itself as a property: https://github.com/asyncly/EventEmitter2/blob/master/lib/eventemitter2.js#L38

```
  function EventEmitter(conf) {
    this._events = {};
    this.newListener = false;
    configure.call(this, conf);
  }

  EventEmitter.EventEmitter = EventEmitter;
```

**Comment by kmalakoff** [comment]
Here's a pull request: https://github.com/asyncly/EventEmitter2/pull/156
