### ISSUE TITLE
Can i addListener after emit was fiered ?

### ISSUE THREAD

**Issue by muxahuk** [asyncly/EventEmitter2#147]
Hello,

I need a solution how to fire all addListener events on emit when emit is called.

```javascript
var EventEmitter = require( "eventemitter2" ).EventEmitter2;
var events = new EventEmitter();

events.on( 'filter', function() {
	console.log( 'filter 1' );
} );

var num = events.emit( 'filter' );

events.on( 'filter', function() {
	console.log( 'filter 2' );
} );
```

I want my console.log show both `filter 1` and `filter 2`, but now, there's only `filter 1`..
what possible fix could be for that ?

**Comment by RangerMauve** [comment]
For that you'd have to buffer all events that occured beforehand, and it'd be a potential memory leak.

A better solution would be to ensure that you add the even listeners before you emit the event. Maybe emit the event asynchronously? Something like [asap](https://www.npmjs.com/package/asap) could be useful for that.

**Comment by RangerMauve** [comment]
Gonna close this to clean up. Feel free to comment and reopen if you need more help.
