### ISSUE TITLE
EventEmitter2 doesn't work in IE10

### ISSUE THREAD

**Issue by Stratus3D** [asyncly/EventEmitter2#149]
When using EventEmitter2 on IE10 I got a "(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit." warning one time. Immediately after the warning I got a TypeError: "TypeError: Object doesn't support property or method 'trace'". It looks like the error was caused by the call to `console.trace` on either this line: https://github.com/asyncly/EventEmitter2/blob/b10d535456d98a71ebf3aa9f16d5d56014b3bd39/lib/eventemitter2.js#L206 or this line: https://github.com/asyncly/EventEmitter2/blob/b10d535456d98a71ebf3aa9f16d5d56014b3bd39/lib/eventemitter2.js#L398. IE10 doesn't have a trace method on it's log object so the error was raised.

I looked for the supported browsers but couldn't find a list here on GitHub. I assumed IE10 wasn't supported until I saw issue #148, in which @RangerMauve stated that it should work with IE9+.

**Questions**
* Is IE10 supported?
* If so, is there a workaround for this issue?

**Comment by RangerMauve** [comment]
Good catch. For now try defining console.trace as a moop.  I'll put in logic to fix that later tonight. Else a PR would be welcome

**Comment by RangerMauve** [comment]
@hij1nx @jasonkuhrt Could one of you guys make a new release for this?

**Comment by jasonkuhrt** [comment]
@hij1nx Just give @RangerMauve `npm` access too?
