### ISSUE TITLE
Wildcard support for multiple paths

### ISSUE THREAD

**Issue by panuhorsmalahti** [asyncly/EventEmitter2#154]
Currently,
```
emitter.on("foo.*", callback);
```

Doesn't match the foo.bar.zoo event. It would be nice to get support for this use case.

**Comment by foxbenjaminfox** [comment]
You can use a double asterisk to match an arbitrary number of levels. (Zero or more.)

In your case, you'd use `emitter.on("foo.**", callback);`, which would match any of the events `"foo"`, `"foo.bar"`, `"foo.bar.baz"`, and so forth.

I just now submitted a pull request to add to the README  documentation on this hidden feature. It's not that this wasn't supported, it's just that you had no way of knowing (short of reading the code) that this feature existed.

**Comment by 0x00A** [comment]
@foxbenjaminfox :+1: merged.
