### ISSUE TITLE
Attach listener to multiple events

### ISSUE THREAD

**Issue by viveleroi** [asyncly/EventEmitter2#157]
Occasionally, we need to listen to two events with the same listener. Either by giving an array or a character-separated-list, we should be able to do this in one line.

Currently, we have to do:

    tree.on('node.selected', handler);
    tree.on('node.deselected', handler);

This should allow condensing

    tree.on(['node.selected', 'node.deselected'], handler);

**Comment by RangerMauve** [comment]
Not a fan of overloaded method signatures, especially since this is very different from the regular EventEmitter API.
