### ISSUE TITLE
Exports function not object on browser

### ISSUE THREAD

**Issue by thejmazz** [asyncly/EventEmitter2#161]
Let me know if I'm doing anything wrong...but when using my module on the browser..got `undefined is not a function`:

In Node this works:

```js
const EventEmitter2 = require('eventemitter2').EventEmitter2
```

but in the browser no object is returned, and instead need to do this with the exported function:

```js
const EventEmitter2 = require('eventemitter2')
```

Bunding with webpack, babel.

**Comment by RangerMauve** [comment]
What version are you using specifically?

**Comment by thejmazz** [comment]
`0.4.14`

**Comment by RangerMauve** [comment]
Could you try installing the version on `master` in github? It hasn't been released yet and your issue may have been fixed by #156

**Comment by thejmazz** [comment]
Sure, I'll get to it in a few hours/days. Right now I pushed a patch that just does 

```js
const EventEmitter2 = require('eventemitter2').EventEmitter2 || require('eventemitter2')
``` 
lol. So *my* module works.. what's the best way to install from `master`? `npm link`?

**Comment by RangerMauve** [comment]
@thejmazz You can do a `npm install asyncly/eventemitter2` which should be enough.

I've been pretty busy, too. >.< Hopefully will have some time to get around to doing some testing / documenting for the new changes before the next release.

**Comment by RangerMauve** [comment]
Gonna close this since #156 is about to be part of the release. Do re-open it if you still have issues after upgrading.

**Comment by thejmazz** [comment]
Sounds good, I'll let you know.

**Comment by RangerMauve** [comment]
1.0.0 is out with this, and some other fixes, by the way.

**Comment by thejmazz** [comment]
Nice, congrats on the big "one-point-oh"!
