### ISSUE TITLE
TypeError: Cannot read property 'call' of undefined ~ 1.0.1

### ISSUE THREAD

**Issue by dhoko** [asyncly/EventEmitter2#164]
Since the 1.0.1 i've got some errors, I've patched some of them (Calling emitter.off after an emitter.on creates an error now, I couldn't use `once` because of a condition). But this one is weird:

From L 341:
```js
case 2:
  handler[i].call(this, arguments[1])
```

```
vendor.min.js:13550 TypeError: Cannot read property 'call' of undefined
    at EventEmitter.emit (http://10.0.1.200:3000/js/vendor.min.js:33265:21)
```

debug:

```js
for (i = 0, l = handler.length; i < l; i++) {
 this.event = type;

 if('clientLocation.LOCATION' === arguments[0]) {
   debugger
 }
```

| Iteration |  i |  l |  handler.length | 
|-----------|----|----|-----------------| 
| 1         |  0 |  7 |  7              | 
| 2         |  1 |  7 |  7              | 
| 3         |  2 |  7 |  6              | 
| 4         |  3 |  7 |  5              | 
| 5         |  4 |  7 |  4              | 

Didn't change anything except upgrading to the 1.0.1.

Edit:
Ok here is the problem, i've got:
- 1 `on`
- 6 `once`

So when the event is triggered with once we've got this function executed (L 250):
```js
function listener() {
  if (--ttl === 0) {
    self.off(event, listener);
  }
  fn.apply(this, arguments);
}
```
and it will remove them from `this._events[type]` -> [cf L 575](https://github.com/asyncly/EventEmitter2/blob/master/lib/eventemitter2.js#L575). So the for loop is false, because it doesn't restart its iteraton

**Comment by dhoko** [comment]
Bug sample:

```js
var EventEmitter2 = require('../../lib/eventemitter2').EventEmitter2;
var emitter2 = new EventEmitter2;


emitter2.once('test', () => console.log('test'))
emitter2.on('test', () => console.log('test'))

emitter2.emit('test', {name: 42})
```

```$ node bug.js 
test
/home/dhoko/dev/EventEmitter2/lib/eventemitter2.js:341
          handler[i].call(this, arguments[1]);
                    ^

TypeError: Cannot read property 'call' of undefined
    at EventEmitter.emit (/home/dhoko/dev/EventEmitter2/lib/eventemitter2.js:341:21)
    at Object.<anonymous> (/home/dhoko/dev/EventEmitter2/test/perf/bug.js:14:10)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

```

**Comment by RangerMauve** [comment]
Oh jeeze, @sergeyksv any idea why your changes might have caused this? Have you guys seen this in your use of the library?

**Comment by sergeyksv** [comment]
This looks to be pretty generic behaviour and have to be covered by current test. Let me check it.

**Comment by sergeyksv** [comment]
Yes that was regression issue with our fix that was not covered by tests. Fixes issue and added test that verify it. Submitted push request.

**Comment by RangerMauve** [comment]
@dhoko Does 1.0.2 fix this for you?

**Comment by dhoko** [comment]
Yup thanks @sergeyksv
