### ISSUE TITLE
Multi-level mask and wildcard in event

### ISSUE THREAD

**Issue by moteus** [asyncly/EventEmitter2#169]
Test case
```JS
var server = new em.EventEmitter2({wildcard: true, delimiter: '::'})
function test (value1, value2) { console.log('e0', this.event); }
server.on('A::**::C', test);
server.emit('A::*') // not called
server.emit('A::C') // called
```
According documentation I think it should calls both listener.

**Comment by shvelo** [comment]
You are subscribing to `A::**::C`, and there is no `C` in the first event name

**Comment by moteus** [comment]
But `A::*` means match any and `**` allows match zero level `A::**::C` so
```JS
server.on('A::C',     function() { console.log('A::C Match', this.event); });
server.on('A::**::C', function() { console.log('A::C Match', this.event); });
server.emit('A::*')     // match to 'A::C'
server.emit('A::C')    // match to 'A::C' and to `A::**::C`
```

But I really do not use this library and it is not big problem because I do not think this have some real usecase. I just try figure out how it should works to be able implement EventEmitter on Lua language. In fact I found similar problem with

```JS
server.on('A::**', test);
server.emit('A::*')       // called
server.emit('A::*::B')    // not called
```

**Comment by shvelo** [comment]
You're right.

I don't really understand the basis of allowing wildcards in `emit` though

**Comment by priitpl** [comment]
Hm ... don't see any point too...
Better to close to not confuse other developers.
Only listeners uses wildcard to subscribe.
This is definitely not the publisher responsibility to use wildcard for defining the group of subscribers.
