### ISSUE TITLE
Wildcard matching isn't working

### ISSUE THREAD

**Issue by rajashekhargundeti** [asyncly/EventEmitter2#174]
Hi,
var e2 = require('eventemitter2').EventEmitter2;
var server = new e2({wildcard: true, delimiter: ','});
server.on('h.*end', function(){ console.log("from h.*end :" + this.event); } );

server.emit('hello1end'); // is not getting caught.

server.emit('h.*end'); // this is working. exact match

From wildcard section, '*' is working..it is capturing all events.

**Comment by Grayda** [comment]
@rajashekhargundeti Looks like you've got delimiter set up as a comma (`,`), but your emitted events are using a period (`.`). That could be a typo though

I just ran this test, and it worked fine:

```
var EventEmitter2 = require("eventemitter2").EventEmitter2
var emitter = new EventEmitter2({ wildcard: true })

// Change this to "**" to catch ALL events, leave as "*" to catch top-level events
emitter.on("*", function(data) {
  console.log(this.event + " was emitted with " + data)
})

emitter.on("test.*", function(data) {
  console.log("Something in the test namespace was emitted: " + this.event + " with " + data)
})

emitter.emit("test.hello", "world") // Will show "Something in the test namespace ..."
emitter.emit("test.hello.foo", "bar") // Won't show anything, because * only searches same level
emitter.emit("abc", "def") // Will show "abc was emitted with def"
emitter.emit("different.namespace", "cosmic") // Won't show anything, because * only searches same level
```

Which yields this output:

```
Something in the test namespace was emitted: test.hello with world
abc was emitted with def
```

Which is the output I expect.

**Comment by 0x00A** [comment]
@Grayda looks like he solved this, closing.
