### ISSUE TITLE
RxJS implementation

### ISSUE THREAD

**Issue by 2beers** [asyncly/EventEmitter2#176]
Hello. I just found your library. Any chances for future versions to be based on RxJS?
This is a small example on how to build a simple event emitter: https://github.com/Reactive-Extensions/RxJS/blob/master/doc/howdoi/eventemitter.md

I would love to have something like EventEmitter2 options like wildcards but to return Observables.

Cheers

**Comment by RangerMauve** [comment]
Moving to RxJS would be a pretty huge breaking change. It would make more sense to just fork it and start a new project.

Maybe have a wrapper over top of EventEmitter's API which uses RxJS.
