### ISSUE TITLE
Errors in Typescript .d.ts file

### ISSUE THREAD

**Issue by LivesleyWA** [asyncly/EventEmitter2#188]
interface emitter {
        emit(event: string| string[],...values: any[]);
        emitAsync(event: string): Promise<any[]>;
        addListener(event: string, listener: Listener);
        on(event: string, listener: Listener);
        once(event: string, listener: Listener);
        many(event: string, timesToListen: number, listener: Listener);
        many(events: string[], listener: Listener);
        onAny(listener: EventAndListener);
        offAny(listener: Listener);
        removeListener(event: string, listener: Listener);
        off(event: string, listener: Listener);
        removeAllListeners(evetns?: string[]);
        setMaxListeners(n: number);
        listeners(event: string): ()=>{}[] // TODO: not in documentation by Willian
        listenersAny():           ()=>{}[] // TODO: not in documentation by Willian
    }

Function declarations in the emitter interface which lack return types must have return types specified otherwise errors may be generated. For example, _'emit' which lacks return-type annotation, implicitly has an 'any' return type._

**Comment by RangerMauve** [comment]
Somebody tried to fix this with #177 , but they didn't end up getting it to work. A PR that properly addresses the issue would be very much appreciated

**Comment by LivesleyWA** [comment]
I took a look at this. It looks like the latest version is correct. However, something is referencing an earlier version, 1.0.5. I'll see if I can work out what and ask them to update.

You can close this thanks.

**Comment by RangerMauve** [comment]
Sounds good!
