### ISSUE TITLE
eventemitter2.d.ts class EventEmitter2 breaks sublime color syntax

### ISSUE THREAD

**Issue by roblav96** [asyncly/EventEmitter2#191]
So the `2` at the end of `EventEmitter2` causes my sublime color syntax to be drunk af.

## Drunk Sublime
![drunk](http://i.imgur.com/WneKTmF.png)

## Sober Sublime
![sober](http://i.imgur.com/2BIQ9ON.png)

I know this isn't that big of a deal, I'm remedying the situation like this:
```typescript
import {EventEmitter2 as EventEmitterTwo} from "eventemitter2"
```
But I thought I'd drop a line incase it worried you.

Awesome module mate! I love it 🍰

**Comment by RangerMauve** [comment]
That's really weird. :P Not sure if this would warrent an addition to the README, but I'm sure anyone else having this problem will find this issue.

As an alternative, I like to name it `EventEmitter` without the 2.

Thanks for reporting!

**Comment by roblav96** [comment]
No problem mate! A rename to `EventEmitter` sounds good. Also quick, do you have plans to integrate some sort of `context` parameter like https://github.com/primus/eventemitter3 does?

**Comment by RangerMauve** [comment]
I don't think it's been brought up anywhere. It might be a bit harder because `EventEmitter2.emit` can take multiple arguments to be passed into the callback.

E.g.

```
emitter.on("hello", function(a, b, c, d){
 console.log("world", a, b, c, d);
});
emitter.emit("hello", 1,2,3,4);
```
