### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by sebakerckhof** [asyncly/EventEmitter2#192]
While checking for outdated NPM packages I noticed that I use eventemitter2 1.0.5 instead of latest 2.1.3.
Following semver, this would mean a major update with possibly breaking changes, but I can't seem to find any changelog information and browsing through the commits for possible breaking changes is well...cumbersome and dangerous to miss something.

Is there any information regarding BC-breaking changes?

**Comment by RangerMauve** [comment]
Hi, sorry for not keeping track of changes in a nicer format. I'll make sure to do this from now on and will open an issue about it.
For the 2.0.0 release, the only thing that changed was #170 which changed the behavior of `onAny` when emitting more than 3 arguments which was broken before.

**Comment by RangerMauve** [comment]
Released as part of version 2.2.0
