### ISSUE TITLE
wrong typing for removeAllListeners

### ISSUE THREAD

**Issue by gitawego** [asyncly/EventEmitter2#199]
it gives error for my code:
```js
const topic = "sync/start";
this.removeAllListeners(topic);
```

I think this method's interface would be defined like:

```
removeAllListeners(evetns?: string | string[]): emitter;
```

plus, this definition gives impression that you can put multiples event names, like this:

```js
this.removeAllListeners(['sync/update','sync/restart']);
```

which will be failed to remove these two events' listeners.

**Comment by RangerMauve** [comment]
A pull request for this would be very welcome!
