### ISSUE TITLE
Not compatible with node event emitter

### ISSUE THREAD

**Issue by sebakerckhof** [asyncly/EventEmitter2#208]
Node event emitter (since version 6) contains the function `eventNames()` that lists the event names:
https://nodejs.org/api/events.html#events_emitter_eventnames

This library does not provide this function and is therefore no full implementation of the node event emitter.

**Comment by RangerMauve** [comment]
Good catch! We haven't been updating to conform to new EventEmitter methods, but that's mostly because it just wasn't a focus. A pull request for this method would be very much appreciated!
