### ISSUE TITLE
Shouldn't listeners() include the any event listeners?

### ISSUE THREAD

**Issue by sebakerckhof** [asyncly/EventEmitter2#209]
Currently the `listeners()` function doesn't include the listeners from the `_all` array. 

Wouldn't it make sense to include the any listeners?

**Comment by RangerMauve** [comment]
The `any` listeners can't be removed with `removeListener` and they're fairly different from regular listeners, I think it makes more sense to separate them, tbh.

What would be the main reason for including them?

**Comment by sebakerckhof** [comment]
Yeah, I guess it would depend on the use case.
I was expecting `listeners` to give me the list of every function that would receive a certain event when triggered. It's because I basically proxy events from a third-party API in my node app. And as soon as someone subscribes to one event from a certain set of events, it should subscribe for the event with the third-party API. When connection is lost and restored with the third party API I have to resubscribe and I was using the `listeners` method for that.

Anyway, I guess it makes sense not to include it, since it's impossible to trigger correct 'newListener' events for `any` listeners, so that makes them special indeed.
