### ISSUE TITLE
Make wildcard description clearer in README

### ISSUE THREAD

**Issue by sunny-lan** [asyncly/EventEmitter2#219]
**TLDR - Add the following in the API section of `README.md`:**

> The event name can contain multiple wildcards. For example:
> ```
> "a.*.b.*" // this would match for example, "a.x.b.y"
> ```

**Reason:**

The README has the following section about wildcards:

>An event name passed to any event emitter method can contain a wild card (the * character). If the event name is a string, a wildcard may appear as foo.*. If the event name is an array, the wildcard may appear as ['foo', '*']`.
>
>If either of the above described events were passed to the on method, subsequent emits such as the following would be observed...
>```
>emitter.emit('foo.bazz');
>emitter.emit(['foo', 'bar']);
>```

The wording is a bit confusing here as wildcard is described singularly:

>  any event emitter method can contain a wild card
> the wildcard may appear as ['foo', '*'].

Which makes it sound as if only one wildcard is allowed per event name. The only way to find out otherwise is to test it yourself, which isn't that hard, but still annoying.

**Comment by RangerMauve** [comment]
A PR to improve this would be very much appreciated!
