### ISSUE TITLE
Reset for testing

### ISSUE THREAD

**Issue by fgarcia** [asyncly/EventEmitter2#223]
In one of my tests I was capturing all events, something like this:

    global.bus.onAny( () => {
      console.log('Event')
    })

That was fine for a while, but once I told my test suite to **--watch** my code I started getting the log repeated. The number of duplicated log lines increased every run.

Obviously the cause was that now under **--watch** the test suite never ended properly (the process never terminates). A new listener was attached every time the test ran. 

I thought that a way to remove all listeners was just `global.bus.removeAllListeners()` but that did not work. I did try with a whole new instance `global.bus = new EvetEmitter2()` that did solve the original problem, but introduced lots of nasty side effects because some other parts of my code *remembered* the old bus instance.

Currently I am solving my test resets with `global.bus._all = []` but that is just a dirty hack. Is there any more elegant solution?

**Comment by RangerMauve** [comment]
Using `global.bus.offAny()` with no argument should [clear the listener list](https://github.com/asyncly/EventEmitter2/blob/master/lib/eventemitter2.js#L696). Seems like this is missing from the docs.

A PR with the documentation changes would be very welcome!

**Comment by fgarcia** [comment]
Did not work for me. But I managed to create a very clear example of my problem 

https://gist.github.com/fgarcia/043c1afac5a5b6ef6edd4aed739a8cb0

The `bus.offAny()` raises an exception

I think the whole gist is a good note about how to use EventEmitter safely

**Comment by fgarcia** [comment]
Closing the issue for the time being because I am trying to understand myself this topic. Right now I can't tell apart clever ideas from tragic mistakes.
