### ISSUE TITLE
I cant get this to work. Help wanted.

### ISSUE THREAD

**Issue by parthgandhi7** [asyncly/EventEmitter2#224]
I have two components in react native. I am trying to fire an event from one and trying to catch the event in the other event. But it does not work. Please help.
component1.js
```
var EventEmitter2 = require('eventemitter2').EventEmitter2;
var server = new EventEmitter2();
server.emit('STORE_SELECTED', selectedStore);

```

component2.js
```
var EventEmitter2 = require('eventemitter2').EventEmitter2;
var listener = new EventEmitter2();
class component2 extends Component {
  componentWillMount() {
    listener.on('STORE_SELECTED', (value) => {
      console.log('event store selected', value);
    });
  }

  componentWillUnmount() {
    listener.removeListener('STORE_SELECTED');
  }
}
```

Can you please point me out what is wrong? There is no error message showing up but the `console.log` in the listener should get printed?
It would be better if you can provide me with a proper working code sample.
Thanks.

**Comment by parthgandhi7** [comment]
Anybody having problem like me, can use [this library](https://github.com/kmend/react-native-eventemitter) instead. It is a wrapper over event emitter2 but with a way easier and understandable implementation.

**Comment by RangerMauve** [comment]
You're creating two separate isntances of EventEmitter2, you should pass the instance of the event emitter in the context or as a prop.

**Comment by parthgandhi7** [comment]
My whole point of using events was that i could pass and use some params between 2 totally unrelated components . If i had to use context and/or props why should i be using event emitter i could have directly passed my param in the context . Why would i be passing your event emitter instance in context and then using it for accessing params. I think you should be considering this as a feature request or something to implement something like [this](https://github.com/kmend/react-native-eventemitter) , where you just require the package in any file within the app and emit and listen to events globally. I guess thats the whole point of events. To emit event from any page and to listen to event and reacting on it on some other page. Events instance should be global by default.
