### ISSUE TITLE
[Feature Request] All unhandled events

### ISSUE THREAD

**Issue by rdrey** [asyncly/EventEmitter2#72]
Hey Paolo

I'd love to do a kind of `pipe` to another EventEmitter for all events that haven't been handled by my component.

The API I have in mind is the following:

    server.on('foo.*', function(value1, value2) {
      console.log(this.event, value1, value2);
    }).on('bar.baz', function(value1, value2) {
      console.log(this.event, value1, value2);
    }).unhandled(function(value1, value2) {
      // Any event not in 'foo.*' or 'bar.baz':
      console.log(this.event, value1, value2); 
    });

`unhandled` could be `onOther` or whatever else fits into the EventEmitter style.

What do you think, could this be low-level enough to be useful for everyone else?

**Comment by RangerMauve** [comment]
You can listen on "all" events using `onAny`, should be easy enough to make a wrapper or utility to enable this functionality. Also, adding state to the result of `on` doesn't seem like it'd be good for performance.
