### ISSUE TITLE
Avoid calling 'this.emit' when 'this.newListener' is false

### ISSUE THREAD

**Issue by drodsou** [asyncly/EventEmitter2#78]
Instead of always calling `this.emit` from `EventEmitter.prototype.on` and making the check for `this.newListener` in the emit method, wouldn't it be better just to make a conditional call to `this.emit` from `EventEmitter.prototype.on` only if `this.newListener` is true?. Eg, replacing line 356 by:

    if (this.newListener === true) {
        this.emit('newListener', type, listener);
    } 

Maybe I'm missing something, but the current behaviour may be strange for someone extending EventEmitter2 and the emit method, as I was doing :-)

Regards.

**Comment by fresheneesz** [comment]
I'm reading some of these old issues and I'm wondering if ones like this are closable, or if the project is stagnant..

**Comment by RangerMauve** [comment]
Closing
