### ISSUE TITLE
EventEmitter.listeners("*") does not return all listeners

### ISSUE THREAD

**Issue by ghost** [asyncly/EventEmitter2#88]
EventEmitter.listeners("*") does not return all listeners. The wildcard should expand to all events. Currently, EventEmitter.listeners("*") acts like EventEmitter.listenersAny(). If that is the desired approach, EventEmitter.listenersAny() is redundant and users can use EventEmitter.listeners("*").

However, EventEmitter.listeners("*")  could return all listeners. And EventEmitter.listenersAny() should probably be deprecated and replaced with EventEmitter.listenersOnAny(), a more intuitive naming and avoiding redundancy.

IMHO

**Comment by RangerMauve** [comment]
Closing this since `ee.listeners()` does actually contain the wanted functionality.
