### ISSUE TITLE
Globstar

### ISSUE THREAD

**Issue by bananushka** [asyncly/EventEmitter2#95]
Are there any plans to support a globstar wildcard in events? For example `emitter.on(['foo', '**'], cb)`, for any event that starts with `foo`, and may have zero or more sub-namespaces, or even `emitter.on(['**', 'foo', '**'], cb)`, for any event that contains `foo`. I've read in #72 that you're planning on making the wildcard system pluggable. Is that still relevant, and will it be possible to have globstar functionalty by those means?

**Comment by RangerMauve** [comment]
Closing due to lack of interest in 3 years
