### ISSUE TITLE
RegExp

### ISSUE THREAD

**Issue by brunoduran** [asyncly/EventEmitter2#99]
I just have looking in the issues and I'm curious about regular expression support. It seems that never have showed up in the repository talks. It would be a nice enhancement.

Im obviously taking about using them as listener, like:

```javascript
object.on(/client\d{3}/, function(data){
  //some logic here
});
```

**Comment by RangerMauve** [comment]
Try something like [pattern-emitter](https://www.npmjs.com/package/pattern-emitter) for now.
